version: "3.9"
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    # no volume to keep node_modules from image
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    depends_on:
      - backend
